version: "2"
services:
  web:
    container_name: tim-module
    build: .
    ports:
    - "80:3000"
    links:
    - mysql
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yongsoolee
      MYSQL_DATABASE: shoedidas
      MYSQL_USER: root
      MYSQL_PASSWORD: yongsoolee